# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
ci:
  skip: [pylint]

repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: local
    hooks:
      - id: pylint
        name: Lint Python code with pylint
        entry: pylint
        language: system
        types: [python]
        args: ["-rn", "--rcfile=pyproject.toml"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        name: Don't allow commits to the main branch
        args: ["--branch", "main"]
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Check that file end with a newline character
      - id: check-added-large-files
        name: Check for large files
      - id: check-json
        name: Check JSON files are valid and parseable
      - id: check-yaml
        name: Check YAML files are valid and parseable
      - id: check-ast
        name: Validate Python

  # Formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
        name: Make code pretty

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
        name: Align Python code to latest syntax

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: Check Python formatting

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sort Python import statements
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2
    hooks:
      - id: pycln
        name: Remove unused imports and variables
        args: [--config=pyproject.toml]
