[build-system]
requires = [
    "setuptools >= 47.6",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=db_query_profiler"
testpaths = [
    "tests",
]
